compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

nmMode: hardlinks-local
pnpMode: loose

packageExtensions:
  "@medusajs/types@*":
    peerDependencies:
      "awilix": "*"
